service:
  name: twitch-hosting-prototype

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stackName: twitch-hosting-prototype
  role: arn:aws:iam::646279979860:role/twitch_hosting_prototype_lambda

functions:
  twitch-hosting-prototype:
    handler: src/handler.entrypoint
